import json
import csv
from pathlib import Path
from typing import List, Any
from pydantic import BaseModel
from datetime import date, datetime

class DataExporter:
    """Handles exporting generated data to files (JSON, CSV, SQL)"""

    @staticmethod
    def export(data: List[Any], filename: str):
        """Export data based on file extension"""
        path = Path(filename)
        extension = path.suffix.lower()

        if extension == ".json":
            DataExporter._to_json(data, path)
        elif extension == ".csv":
            DataExporter._to_csv(data, path)
        elif extension == ".sql":
            DataExporter._to_sql(data, path)
        else:
            raise ValueError(f"Unsupported format: {extension}")

    @staticmethod
    def _to_json(data: List[Any], path: Path):
        """Save as JSON"""
        json_ready = [
            item.model_dump() if isinstance(item, BaseModel) else item.__dict__
            for item in data
        ]
        
        # המרה של תאריכים למחרוזות כדי ש-JSON לא ייכשל
        json_ready = json.loads(json.dumps(json_ready, default=str))

        with open(path, "w", encoding="utf-8") as f:
            json.dump(json_ready, f, indent=2)
        
        print(f"✅ Successfully exported {len(data)} items to {path}")

    @staticmethod
    def _to_csv(data: List[Any], path: Path):
        """Save as CSV"""
        if not data:
            return

        first_item = data[0]
        if isinstance(first_item, BaseModel):
            headers = first_item.model_dump().keys()
            rows = [item.model_dump() for item in data]
        else:
            headers = first_item.__dict__.keys()
            rows = [item.__dict__ for item in data]

        with open(path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=headers)
            writer.writeheader()
            writer.writerows(rows)
            
        print(f"✅ Successfully exported {len(data)} items to {path}")

    @staticmethod
    def _to_sql(data: List[Any], path: Path):
        """Save as SQL INSERT statements"""
        if not data:
            return

        table_name = data[0].__class__.__name__.lower() + "s" # Customer -> customers
        
        with open(path, "w", encoding="utf-8") as f:
            f.write("-- Auto-generated by FixtureForge\n")
            f.write(f"-- Target Table: {table_name}\n\n")

            for item in data:
                # המרה למילון
                record = item.model_dump() if isinstance(item, BaseModel) else item.__dict__
                
                columns = ", ".join(record.keys())
                values = []
                
                for v in record.values():
                    if isinstance(v, (str, date, datetime)):
                  
                        clean_v = str(v).replace("'", "''")
                        values.append(f"'{clean_v}'")
                    elif v is None:
                        values.append("NULL")
                    else:
                        values.append(str(v))
                
                vals_str = ", ".join(values)
                sql_stmt = f"INSERT INTO {table_name} ({columns}) VALUES ({vals_str});\n"
                f.write(sql_stmt)

        print(f"✅ Successfully exported {len(data)} SQL statements to {path}")