"""
IntelligentRouter — classifies every model field into a generation tier.

Tiers (aligned with the FixtureForge strategic plan):
  STRUCTURAL  — Primary keys, foreign keys, auto-increment IDs.
                Generated by internal counters / registry lookups.
                Cost: zero.

  STANDARD    — Well-known patterns: name, email, phone, address, date, URL.
                Generated by Faker.
                Cost: zero.

  COMPUTED    — Pydantic @computed_field properties that calculate their own
                value from other fields (e.g. total = price * qty).
                The generator skips these entirely — Pydantic handles them.
                Cost: zero.

  SEMANTIC    — Free-text fields requiring linguistic intelligence: bios,
                reviews, descriptions, chat messages, JSON payloads, etc.
                Generated by an LLM (Tier 3 → cheap SLM / Tier 4 → capable LLM).
                Cost: API tokens.
"""
from enum import Enum, auto

from .parser import FieldInfo


class FieldTier(Enum):
    STRUCTURAL = auto()
    STANDARD   = auto()
    COMPUTED   = auto()
    SEMANTIC   = auto()


class IntelligentRouter:
    """
    Classifies a FieldInfo into the appropriate FieldTier.
    Rules are evaluated top-to-bottom; first match wins.
    """

    # --- keyword lists (lower-case) ---
    _STRUCTURAL_SUFFIXES = ("_id",)
    _STRUCTURAL_EXACT    = ("id",)

    _STANDARD_KEYWORDS = (
        "name", "email", "phone", "address", "city",
        "country", "state", "zip", "postal", "date",
        "time", "url", "link", "website", "username",
        "avatar", "image", "photo", "age", "gender",
        "price", "amount", "salary", "score", "rating",
        "quantity", "qty", "weight", "height",
    )

    _SEMANTIC_KEYWORDS = (
        "description", "bio", "review", "comment", "reason",
        "message", "content", "summary", "feedback", "about",
        "story", "notes", "remarks", "details", "body",
        "text", "narrative", "excerpt", "caption", "subtitle",
        "question", "answer", "prompt", "response", "transcript",
        "report", "log", "complaint", "memo",
    )

    # Fields with free text longer than this threshold go to AI
    _LONG_TEXT_THRESHOLD = 150

    def classify(self, field: FieldInfo) -> FieldTier:
        # 1. Pydantic @computed_field — never generate, skip entirely
        if field.metadata.get("computed"):
            return FieldTier.COMPUTED

        name = field.name.lower()
        type_str = field.type_name.lower()
        constraints = field.constraints

        # 2. Structural: explicit primary_key constraint
        if constraints.get("primary_key"):
            return FieldTier.STRUCTURAL

        # 3. Structural: exact "id" or "*_id" naming (but not "valid_id", "uuid_*")
        is_id_name = (
            name in self._STRUCTURAL_EXACT
            or (
                any(name.endswith(suffix) for suffix in self._STRUCTURAL_SUFFIXES)
                and "valid" not in name
                and "uuid" not in name
            )
        )
        if is_id_name and "int" in type_str:
            return FieldTier.STRUCTURAL

        # 4. Standard: named patterns take priority (name, email, phone, …)
        #    Checked BEFORE semantic so well-known fields are never sent to AI.
        #    Use word-boundary matching (split by "_") to avoid false positives
        #    like "age" matching "message", or "name" matching "filename".
        name_parts = set(name.split("_"))
        if any(kw in name_parts for kw in self._STANDARD_KEYWORDS):
            return FieldTier.STANDARD

        # 5. Semantic: explicit keyword match on string fields
        if "str" in type_str:
            if any(kw in name_parts for kw in self._SEMANTIC_KEYWORDS):
                return FieldTier.SEMANTIC

            # 6. Semantic: unconstrained / very long string fields
            #    (no max_length set → assume free text → AI)
            max_len = constraints.get("max_length", 9999)
            if max_len > self._LONG_TEXT_THRESHOLD:
                return FieldTier.SEMANTIC

        # 7. Default fallback → Standard (Faker word / type-based)
        return FieldTier.STANDARD
